version: '3.7'
services:
  webapi:
    network_mode: host
    build: .
    ports:
    - "80:80"
  prometheus:
    network_mode: host
    image: prom/prometheus:v2.9.2
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
    - "9090:9090"
    