version: '3.7'
services:
  webapi:
    build: .
    ports:
    - "80:80"
  prometheus:
    image: prom/prometheus:v2.9.2
    volumes:
      - ./prometheus/:/etc/prometheus/
    links:
    - webapi
    ports:
    - "9090:9090"
    