
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.9.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: vol-prom-cfg
            mountPath: /etc/prometheus/
        ports:
        - containerPort: 9090
      volumes:
        - name: vol-prom-cfg
          configMap:
           name: cfg-prom
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: np-prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    nodePort: 31313
status:
  loadBalancer: {}
